### PR TITLE
Light statsd

### PR DESCRIPTION
**Pull request by amandeepgill-wf**
@shawnrusaw-wf @lyddonb 

Use a modified version of statsd that allows metrics to be toggled off and modify config to turn off sum and sum_squares for timers.  This will save on disk IO and disk use for timers by 33%.

### CODE REVIEW

**Comment by shawnrusaw-wf** [comment]
+1

**Comment by amandeepgill-wf** [comment]
DON'T MERGE THIS.  It doesn't work yet.

**Comment by amandeepgill-wf** [comment]
@shawnrusaw-wf @lyddonb this should work now. There is a test server running this modified docker container now in the MONAN cloud project, and this server is also listed in the servers accessible by grafana as "z_test_lighter_statsd." 

But do we want to merge this into master on this fork?  It uses a modified version of statsd, and this repo is becoming quite specific to Workiva uses.  Perhaps we should get the Workiva org. to make it's own private fork that we can maintain?  We could then also put related docs that might contain Workiva specific info. into the github repo as well.

**Comment by lyddonb** [comment]
@amandeepgill-wf were going to do what we mentioned yesterday and just add a separate dockerfile? I'm honestly fine either way. Just let me know and I can merge whatever.

**Comment by amandeepgill-wf** [comment]
@shawnrusaw-wf @lyddonb I've moved the lighter statsd stuff into it's own Dockerfile, so if there's ever a need or desire to revert to the old one, it can be easily built and run.  If Beau is fine with merging this, it's fine by me.

**Comment by lyddonb** [comment]
Awesome. Looks good. Thanks +1

**Pull request merged**
